#!/usr/bin/env bash
# Setup Nginx web server

if ! which nginx; then
    echo "Installing Nginx";
    apt-get update
    apt-get install nginx -y
fi

echo "Configuring website";
INDEX="Hello World!";
echo "$INDEX" > /var/www/html/index.html;

echo "Restarting nginx";
service nginx restart;
