#!/usr/bin/env bash
# Setup nginx server to redirect

apt-get update
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html;

# sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default;

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-enabled/default;

service nginx restart;
