#!/usr/bin/env bash
# Setup nginx server to custom 404 error page

apt-get update
apt-get install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/404.html;

sed -i '36a rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default;
sed -i '37a error_page 404 /404.html;' /etc/nginx/sites-available/default;

service nginx restart;
