#!/usr/bin/env bash
# Setup nginx server

apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

config=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
      try_files \$uri \$uri/ =404;
    }
    if (\$request_filename ~ redirect_me){
      rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
    error_page 404 /404.html;
    location = /404.html {
      internal;
    }
}"

echo "$config" > /etc/nginx/sites-enabled/default;

service nginx restart;
