#!/usr/bin/env bash
# set up haproxy load balancer

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y update
apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 257141-web-01 3.85.168.234:80 check\n\tserver 257141-web-02 18.234.129.227:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
