#!/usr/bin/env bash
# displays the numbers 1 to 20 and displays

tracker=1
while [ "$tracker" -le 20 ]; do
    echo "$tracker"
    case "$tracker" in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((tracker++))
done
