#!/usr/bin/env bash
# displays the time for 12 trackers and 59 minss

tracker=0
while [ "$tracker" -lt 13 ]; do
    echo "tracker: $tracker"
    mins=1
    while [ "$mins" -lt 60 ]; do
	echo "$mins"
	((mins++))
    done
    ((tracker++))
done
